import math

class Settings:
    AGENTS = 10000

    RED = True
    GREEN = True
    BLUE = False

    SAMPLE_ANGLE = math.pi / 3

    SAMPLE_POSITION_1 = -1 * SAMPLE_ANGLE
    SAMPLE_POSITION_2 = 0
    SAMPLE_POSITION_3 = SAMPLE_ANGLE

    SAMPLE_DISTANCE = 30
    SAMPLE_RADIUS = 5

    ATTRACT_WEIGHT = 1
    AVOID_WEIGHT = 1

    VELOCITY = 2
    COHESION = 1
    TURN_RANDOMNESS = 0.3

    TURN_WEIGHT_1 = (SAMPLE_POSITION_1 * COHESION)
    TURN_WEIGHT_2 = (SAMPLE_POSITION_2 * COHESION)
    TURN_WEIGHT_3 = (SAMPLE_POSITION_3 * COHESION)

    WINDOWX = 1000
    WINDOWY = 900
    WINDOW_SIZE = (WINDOWX, WINDOWY)

    FULLSCREEN = False