import math

class Settings:
    AGENTS = 50000

    RED = True
    GREEN = False
    BLUE = True

    SAMPLE_ANGLE = math.pi / 6

    SAMPLE_DISTANCE = 10
    SAMPLE_RADIUS = 3

    ATTRACT_WEIGHT = 0.3
    AVOID_WEIGHT = -0.1

    VELOCITY = 4
    COHESION = 0.4
    TURN_RANDOMNESS = 0.2

    TURN_WEIGHT_LEFT = (-1 * SAMPLE_ANGLE * COHESION)
    TURN_WEIGHT_RIGHT = (SAMPLE_ANGLE * COHESION)

    FULLSCREEN = False
    WINDOWX = 1200
    WINDOWY = 900
    WINDOW_SIZE = (WINDOWX, WINDOWY)

    SURFACEX = round(WINDOWX * 2)
    SURFACEY = round(WINDOWY * 2)
    SURFACE_SIZE = (SURFACEX, SURFACEY)
